name: CI

on:
  push:
    branches:
    - main

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run TS lint 2021
      run: cd ./2021/ts && ./lint.sh

    - name: Run TS tests 2021
      run: cd ./2021/ts && ./test.sh

    - name: Run TS lint 2022
      run: cd ./2022/ts && ./lint.sh

    - name: Run TS tests 2022
      run: cd ./2022/ts && ./test.sh
